version: '3'
services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
